SteamOS 202410xx upstream

diff --git a/usr/bin/gamescope-session b/usr/bin/gamescope-session
--- a/usr/bin/gamescope-session
+++ b/usr/bin/gamescope-session
@@ -28,6 +28,11 @@ export GAMESCOPE_NV12_COLORSPACE=k_EStreamColorspace_BT601
 
 export STEAM_GAMESCOPE_HDR_SUPPORTED=1
 
+# Workaround older versions of vkd3d-proton setting this
+# too low (desc.BufferCount), resulting in symptoms that are potentially like
+# swapchain starvation.
+export VKD3D_SWAPCHAIN_LATENCY_FRAMES=3
+
 # Make path to gamescope mode save file.
 mkdir -p "$(dirname "$GAMESCOPE_MODE_SAVE_FILE")"
 touch "$GAMESCOPE_MODE_SAVE_FILE"
@@ -61,24 +66,6 @@ export WINE_CPU_TOPOLOGY=${THREADS}:${CPU_TOPOLOGY}
 
 # To expose vram info from radv's patch we're including
 export WINEDLLOVERRIDES=dxgi=n
-
-# Workaround for steam getting killed immediatly during reboot
-# See: jupiter/tasks/-/issues/280
-export STEAMOS_STEAM_REBOOT_SENTINEL="/tmp/steamos-reboot-sentinel"
-if [[ -e "$STEAMOS_STEAM_REBOOT_SENTINEL" ]]; then
-	rm -f "$STEAMOS_STEAM_REBOOT_SENTINEL"
-	/usr/bin/steamos-polkit-helpers/steamos-reboot-now
-	sudo -n reboot
-fi
-
-# Workaround for steam getting killed immediatly during shutdown
-# Same idea as reboot sentinel above
-export STEAMOS_STEAM_SHUTDOWN_SENTINEL="/tmp/steamos-shutdown-sentinel"
-if [[ -e "$STEAMOS_STEAM_SHUTDOWN_SENTINEL" ]]; then
-	rm -f "$STEAMOS_STEAM_SHUTDOWN_SENTINEL"
-	/usr/bin/steamos-polkit-helpers/steamos-poweroff-now
-	sudo -n poweroff
-fi
 
 # Enable dynamic backlight, we have the kernel patch to disable events
 export STEAM_ENABLE_DYNAMIC_BACKLIGHT=1
@@ -182,12 +169,19 @@ if [[ $board_name = "Galileo" ]]; then
 	export STEAM_DISPLAY_REFRESH_LIMITS=45,90
 	export STEAM_GAMESCOPE_FORCE_HDR_DEFAULT=1
 	export STEAM_GAMESCOPE_FORCE_OUTPUT_TO_HDR10PQ_DEFAULT=1
-else
+elif [[ $board_name =~ "Jupiter" ]]; then
 	ui_background=/usr/share/plymouth/themes/steamos/steamos-jupiter.png
 
 	# Set refresh rate range for the legacy refresh swtching UI
 	export STEAM_DISPLAY_REFRESH_LIMITS=40,60
+else
+	ui_background=/usr/share/plymouth/themes/steamos/steamos-jupiter.png
+
+	# Set refresh rate range for the legacy refresh swtching UI
+	export STEAM_DISPLAY_REFRESH_LIMITS=45,60,90,120,144
 fi
+
+
 export STEAM_UPDATEUI_PNG_BACKGROUND=$ui_background
 
 # We previously shipped custom boot animations alongside the OS as uioverrides
@@ -260,12 +254,11 @@ fi
 
 
 VULKANINFO_DEVICES=$(vulkaninfo | grep deviceName | cut -d '=' -f 2)
-GLXINFO_DEVICES_FALLBACK_OLD=$(glxinfo | grep -i renderer | grep -i polaris)
+GLXINFO_DEVICES_FALLBACK_OLD=$(vulkaninfo | grep deviceName | grep -i polaris)
 if [[ "${VULKANINFO_DEVICES}" =~ "Intel(R) UHD" ]]; then
 	echo "Latest Gamescope can be launched, proceeding"
 	# This is already on by default on Galileo, but this enables it on Jupiter too
 	# Re-enable when it becomes less of a hassle
-	#export ENABLE_GAMESCOPE_WSI=1
 	export INTEL_DEBUG=norbc
 	export mesa_glthread=true
 	GAMESCOPEEXEC=gamescope
@@ -274,12 +267,76 @@ elif [[ $GLXINFO_DEVICES_FALLBACK_OLD ]]; then
 	export mesa_glthread=true
 	GAMESCOPEEXEC=gamescope-generic
 else
+	export ENABLE_GAMESCOPE_WSI=1
 	echo "Trying latest gamescope..."
 	export mesa_glthread=true
 	GAMESCOPEEXEC=gamescope
 fi
 
 source holoiso-devicequirk-set
+
+cleanup_loop() {
+    if [ -n "$pid" ]; then
+        kill "$pid"
+    fi
+    exit 0
+}
+
+# Make sure we stop the loop and cleanup properly, with a wait for our
+# children, when we have a recurring background command.
+loop_background() {
+    (
+        pid=
+        trap cleanup_loop TERM
+        while true; do
+            "$@" &
+            pid=$!
+            wait "$pid"
+        done
+    ) &
+}
+
+print_children() {
+    ps h -o pid --ppid "$1" | sed 's/^[[:space:]]*//'
+}
+
+send_signals() {
+    kill -TERM "$@"
+}
+
+cleanup() {
+    local timeout="$1"
+    shift
+    local children=("$@")
+    local sleep_pid pid ret
+
+    # Start a background sleep as a timeout because we don't trust it
+    sleep "$timeout" &
+    sleep_pid=$!
+
+    for pid in "${children[@]}"; do
+        if ! kill -0 "$pid" 2>/dev/null; then
+            continue
+        fi
+
+        # Wait for child or the sleep to finish for timeout purposes
+        ret=0
+        wait -np finished_pid "$pid" "$sleep_pid" || ret=$?
+
+        # Our sleep command finished; we timed out
+        if [[ "$finished_pid" == "$sleep_pid" ]]; then
+            return 2
+        fi
+
+        # Signal received by wait when already in cleanup; bail out
+        if (( ret > 128 )); then
+            return 1
+        fi
+    done
+
+    kill "$sleep_pid"
+}
+
 ${GAMESCOPEEXEC} \
 	--generate-drm-mode fixed \
 	--xwayland-count 2 \
@@ -306,18 +363,18 @@ else
 	# SDDM will restart us
 fi
 
-xbindkeys -f /etc/xbindkeysrc
+xbindkeys -n -f /etc/xbindkeysrc &
 
 steamargs=("-steamos3" "-steampal" "-steamdeck" "-gamepadui")
 
 # Input method support
-/usr/bin/ibus-daemon -d -r --panel=disable --emoji-extension=disable
+/usr/bin/ibus-daemon -r --panel=disable --emoji-extension=disable &
 
 # steamargs+=("-steamfs")
 
 if [[ "${HOLOISO_DEVICE_TYPE}" =~ "SteamDeck" ]]; then
 	(while true; do
-    	/usr/lib/hwsupport/powerbuttond
+    	loop background /usr/lib/hwsupport/powerbuttond
 	done) &
 else
 	(while true; do
@@ -334,33 +391,60 @@ SECONDS=0
 short_session_count=$(< "$short_session_tracker_file" wc -l)
 
 if [[ "$short_session_count" -ge "$short_session_count_before_reset" ]]; then
-	# TODO could detect if we're in the devkit case below and undo that instead
-	# instead of resetting the wrong thing
-	# also could print full list of files and sizes in the Steam dir and save as a diagnostic report
 	echo >&2 "gamescope-session: detected broken Steam, bootstrapping from OS copy..."
 	# at this point, might as well make sure we won't relaunch on a sideloaded build
 	rm -f -- "$HOME/devkit-game/devkit-steam"
 	mkdir -p ~/.local/share/Steam
 	# remove some caches and stateful things known to cause Steam to fail to start if corrupt
 	rm -rf --one-file-system ~/.local/share/Steam/config/widevine
+	# cleanup the steam config dir, i.e. ~/.steam. We should try to preserve registry.vdf if possible
+	steam_config_dir="$HOME/.steam"
+	steam_config_backup_dir="$HOME/dot-steam.bak.$(date +%s)"
+	registry_vdf="$steam_config_dir/registry.vdf"
+	registry_backup_vdf="$steam_config_backup_dir/.steam/registry.vdf"
+	mv "$steam_config_dir" "$steam_config_backup_dir"
+	mkdir -p "$steam_config_dir"
+	cp -f "$registry_backup_vdf" "$registry_vdf" || true
 	# restore clean copy of binaries from RO partition
 	tar xf /usr/lib/steam/bootstraplinux_ubuntu12_32.tar.xz -C ~/.local/share/Steam
 	# rearm
 	rm "$short_session_tracker_file"
 fi
 
+steam_notif_daemon &
+galileo-mura-setup &
+loop_background mangoapp
+
 if [[ -x $HOME/devkit-game/devkit-steam ]]; then
-	steam_notif_daemon &
-	(while true; do
-		mangoapp
-	done) &
-	"$HOME"/devkit-game/devkit-steam "${steamargs[@]}"
+	"$HOME"/devkit-game/devkit-steam "${steamargs[@]}" &
+	steam_wrapper_pid=$!
 else
-	steam_notif_daemon &
-	(while true; do
-		mangoapp
-	done) &
-	steam "${steamargs[@]}"
+	steam "${steamargs[@]}" &
+	steam_wrapper_pid=$!
+fi
+
+kill_steam() {
+	# We need to kill the children of the wrapper, since the wrapper
+	# lacks signal handling (and so killing it does not properly kill
+	# steam)
+	readarray -t pids < <(print_children "$steam_wrapper_pid")
+
+	if [[ "${#pids[@]}" -gt 0 ]]; then
+		kill -TERM "${pids[@]}"
+	else
+		kill -TERM "$steam_wrapper_pid"
+	fi
+}
+
+trap kill_steam TERM
+
+wait "$steam_wrapper_pid"
+exit_code=$?
+
+trap - TERM
+
+if (( exit_code > 128 )); then
+	wait "$steam_wrapper_pid"
 fi
 
 if [[ "$SECONDS" -lt "$short_session_duration" ]]; then
@@ -369,19 +453,16 @@ else
 	rm "$short_session_tracker_file"
 fi
 
-# Ask gamescope to exit nicely
-kill $gamescope_pid
+# Ask all children to exit nicely, now that steam has exited
+readarray -t children < <(print_children $$)
 
-# Start a background sleep for five seconds because we don't trust it
-sleep 5 &
-sleep_pid=$!
+send_signals "${children[@]}"
 
-# Wait for gamescope or the sleep to finish for timeout purposes
-ret=0
-wait -n $gamescope_pid $sleep_pid || ret=$?
+cleanup 5 "${children[@]}"
+cleanup_status=$!
 
 # If we get a SIGTERM/etc while waiting this happens.  Proceed to kill -9 everything but complain
-if [[ $ret = 127 ]]; then
+if (( cleanup_status == 1 )); then
 	echo >&2 "gamescope-session: Interrupted while waiting on teardown, force-killing remaining tasks"
 fi
 
@@ -389,14 +470,14 @@ fi
 # to exit in time or we hit the interrupt case above)
 for job in $(jobs -p); do
 	# Warn about unexpected things
-	if [[ $ret != 127 && $job = "$gamescope_pid" ]]; then
+	if (( cleanup_status == 1 )) && [[ $job = "$gamescope_pid" ]]; then
 		echo >&2 "gamescope-session: gamescope timed out while exiting, killing"
-	elif [[ $ret != 127 && $job != "$sleep_pid" ]]; then
+	elif (( cleanup_status == 1 )) && [[ $job != "$sleep_pid" ]]; then
 		echo >&2 "gamescope-session: unexpected background pid $job at teardown: "
 		# spew some debug about it
 		ps -p "$job" >&2
 	fi
-	kill -9 "$job"
+	kill -KILL "$job"
 done
 
 # This should just be waiting on kill -9'd things. Another signal will cause us to give up, but we should be a little
